/**
 * ===========================================================================
 *  The built-in template library
 * ===========================================================================
 *
 *  -- Why these live in code and not in a table ----------------------------
 *
 *  A template is a starting point for a document, and a starting point that
 *  every organisation gets on day one cannot be seeded per tenant: the seed
 *  would run once, an organisation would edit one of them, and the next
 *  release's improved wording would either overwrite their edit or never
 *  reach them. Both are wrong.
 *
 *  So there are two kinds, and they are different things:
 *
 *    - the library below, shipped with the product, identical everywhere,
 *      never edited in place - using one copies it into a new page, which is
 *      then the organisation's own document;
 *    - `workspace_pages.is_template`, which is an organisation's own template,
 *      written by them, editable by them, and listed beside these.
 *
 *  The gallery shows both and says which is which. Nothing here is stored,
 *  so nothing here can drift from what the code says it is.
 *
 *  -- On the writing ------------------------------------------------------
 *
 *  Every heading is a question somebody actually has to answer, and there are
 *  no headings that exist to make the outline look complete. A template whose
 *  sections get deleted by the first person to use it is worse than no
 *  template, because deleting is more work than typing.
 */

export interface WorkspaceTemplate {
  /** Stable across releases: it is what "new from template" is called with. */
  id: string;
  title: string;
  summary: string;
  category: TemplateCategory;
  kind: 'document' | 'sheet';
  icon: string;
  body: string;
  /** Sheets ship their columns instead of a body. */
  columns?: { name: string; type: string; width?: number; options?: string[]; aggregate?: string; align?: string; formula?: string }[];
  rows?: Record<string, string | number | boolean>[];
}

export type TemplateCategory =
  | 'Meetings' | 'Projects' | 'Sales' | 'Operations' | 'Strategy' | 'People' | 'Planning';

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  'Meetings', 'Projects', 'Sales', 'Operations', 'Strategy', 'People', 'Planning',
];

const today = () => new Date().toISOString().slice(0, 10);

export function builtInTemplates(): WorkspaceTemplate[] {
  const date = today();

  return [
    {
      id: 'meeting-notes',
      title: 'Meeting notes',
      summary: 'Decisions and actions from a single meeting, in the order they happened.',
      category: 'Meetings',
      kind: 'document',
      icon: 'file-text',
      body: [
        '# Meeting notes',
        '',
        `**Date** ${date}  `,
        '**Attendees**   ',
        '**Chair**   ',
        '',
        '## Purpose',
        '',
        'One sentence on why this meeting happened.',
        '',
        '## Discussion',
        '',
        '',
        '## Decisions',
        '',
        '| Decision | Made by | Date |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## Actions',
        '',
        '- [ ] Action, owner, date',
        '',
        '## Not decided',
        '',
        'What was raised and deliberately left open, so it is not raised again as new.',
        '',
      ].join('\n'),
    },
    {
      id: 'project-brief',
      title: 'Project brief',
      summary: 'What the work is, why it matters, and what is out of scope.',
      category: 'Projects',
      kind: 'document',
      icon: 'target',
      body: [
        '# Project brief',
        '',
        '## Summary',
        '',
        'Two or three sentences somebody outside the team could repeat accurately.',
        '',
        '## Background',
        '',
        '## What we are doing',
        '',
        '## What we are not doing',
        '',
        'The most useful section here. Everything left unnamed becomes an argument later.',
        '',
        '## How we will know it worked',
        '',
        '| Measure | Today | Target | By when |',
        '| --- | --- | --- | --- |',
        '|  |  |  |  |',
        '',
        '## Constraints',
        '',
        '- Budget:',
        '- Deadline:',
        '- Dependencies:',
        '',
        '## Who is involved',
        '',
        '| Name | Role | Decision rights |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
      ].join('\n'),
    },
    {
      id: 'project-kickoff',
      title: 'Project kickoff',
      summary: 'The agenda and the record for the meeting that starts a project.',
      category: 'Projects',
      kind: 'document',
      icon: 'map',
      body: [
        '# Project kickoff',
        '',
        `**Project**   `,
        `**Date** ${date}  `,
        '**Attendees**   ',
        '',
        '## Why this project exists',
        '',
        '## Scope, agreed in the room',
        '',
        '**In**',
        '',
        '**Out**',
        '',
        '## The plan',
        '',
        '| Phase | Owner | Starts | Ends |',
        '| --- | --- | --- | --- |',
        '|  |  |  |  |',
        '',
        '## Risks named on day one',
        '',
        '| Risk | Likelihood | Impact | Owner |',
        '| --- | --- | --- | --- |',
        '|  |  |  |  |',
        '',
        '## Ways of working',
        '',
        '- Where the work is tracked:',
        '- How often we meet:',
        '- Who signs things off:',
        '',
        '## Actions out of the kickoff',
        '',
        '- [ ] ',
        '',
      ].join('\n'),
    },
    {
      id: 'project-status',
      title: 'Project status report',
      summary: 'A weekly update that says the position before it says the detail.',
      category: 'Projects',
      kind: 'document',
      icon: 'file-text',
      body: [
        '# Project status report',
        '',
        `**Project**   `,
        `**Week ending** ${date}  `,
        '**Status** On track / At risk / Off track',
        '',
        '## The position',
        '',
        'One paragraph. If somebody reads only this, they should not be surprised later.',
        '',
        '## Done since the last report',
        '',
        '## Next',
        '',
        '## Blocked, and on whom',
        '',
        '| Blocker | Waiting on | Since | Impact if unresolved |',
        '| --- | --- | --- | --- |',
        '|  |  |  |  |',
        '',
        '## Numbers',
        '',
        '| Measure | Plan | Actual |',
        '| --- | --- | --- |',
        '| Budget spent |  |  |',
        '| Milestones complete |  |  |',
        '',
        '## Decisions needed',
        '',
      ].join('\n'),
    },
    {
      id: 'proposal',
      title: 'Proposal',
      summary: 'A client-facing proposal: their problem first, the price last.',
      category: 'Sales',
      kind: 'document',
      icon: 'book-open',
      body: [
        '# Proposal',
        '',
        '**Prepared for**   ',
        `**Date** ${date}  `,
        '**Valid until**   ',
        '',
        '## What you told us',
        '',
        'Their words, not ours. A proposal that opens by describing the seller has already lost.',
        '',
        '## What we propose',
        '',
        '## Scope of work',
        '',
        '| Workstream | What it includes | Deliverable |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## Timeline',
        '',
        '| Phase | Duration | Ends |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## Investment',
        '',
        '| Item | Amount |',
        '| --- | --- |',
        '|  |  |',
        '',
        '## What we need from you',
        '',
        '## Assumptions',
        '',
        'Everything the price depends on. This is the section that settles a dispute.',
        '',
        '## Next steps',
        '',
      ].join('\n'),
    },
    {
      id: 'business-case',
      title: 'Business case',
      summary: 'The argument for spending money, including the option of not spending it.',
      category: 'Strategy',
      kind: 'document',
      icon: 'lightbulb',
      body: [
        '# Business case',
        '',
        '## The decision being asked for',
        '',
        'State it in one sentence, with the amount and the date it is needed by.',
        '',
        '## The problem',
        '',
        '## Options considered',
        '',
        '| Option | Cost | Benefit | Risk |',
        '| --- | --- | --- | --- |',
        '| Do nothing |  |  |  |',
        '|  |  |  |  |',
        '',
        '## Recommendation',
        '',
        '## Financials',
        '',
        '| | Year 1 | Year 2 | Year 3 |',
        '| --- | --- | --- | --- |',
        '| Cost |  |  |  |',
        '| Benefit |  |  |  |',
        '| Net |  |  |  |',
        '',
        '## What could go wrong',
        '',
        '## What happens if we do nothing',
        '',
      ].join('\n'),
    },
    {
      id: 'sop',
      title: 'Standard operating procedure',
      summary: 'A procedure somebody can follow on their first day without asking.',
      category: 'Operations',
      kind: 'document',
      icon: 'code',
      body: [
        '# Standard operating procedure',
        '',
        '**Owner**   ',
        `**Last reviewed** ${date}  `,
        '**Review every** 6 months',
        '',
        '## Purpose',
        '',
        '## When this applies',
        '',
        '## Who does this',
        '',
        '## Before you start',
        '',
        '- ',
        '',
        '## Steps',
        '',
        '1. ',
        '2. ',
        '3. ',
        '',
        '## How to tell it worked',
        '',
        '## When it goes wrong',
        '',
        '| Symptom | Cause | What to do |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## Escalation',
        '',
        'Who to contact, and after how long.',
        '',
      ].join('\n'),
    },
    {
      id: 'policy',
      title: 'Company policy',
      summary: 'A policy with a scope, an owner and a review date, so it can be enforced.',
      category: 'Operations',
      kind: 'document',
      icon: 'book-open',
      body: [
        '# Policy',
        '',
        '**Applies to**   ',
        '**Owner**   ',
        `**Effective from** ${date}  `,
        '**Next review**   ',
        '',
        '## Purpose',
        '',
        '## Scope',
        '',
        'Who this covers, and who it does not.',
        '',
        '## The policy',
        '',
        '## Responsibilities',
        '',
        '| Role | Responsible for |',
        '| --- | --- |',
        '|  |  |',
        '',
        '## Exceptions',
        '',
        'How to request one, and who may grant it.',
        '',
        '## Breaches',
        '',
        '## Related documents',
        '',
      ].join('\n'),
    },
    {
      id: 'business-report',
      title: 'Business report',
      summary: 'A periodic report that leads with the finding, not the method.',
      category: 'Strategy',
      kind: 'document',
      icon: 'file-text',
      body: [
        '# Business report',
        '',
        `**Period**   `,
        `**Prepared** ${date}  `,
        '**Author**   ',
        '',
        '## Headline',
        '',
        'The one thing a reader should take away.',
        '',
        '## Performance',
        '',
        '| Measure | This period | Last period | Change |',
        '| --- | --- | --- | --- |',
        '|  |  |  |  |',
        '',
        '## What drove it',
        '',
        '## What is not working',
        '',
        '## What we are doing about it',
        '',
        '## Outlook',
        '',
        '## Appendix',
        '',
      ].join('\n'),
    },
    {
      id: 'strategy',
      title: 'Strategy document',
      summary: 'Where we are going, what we will not do, and how we will know.',
      category: 'Strategy',
      kind: 'document',
      icon: 'target',
      body: [
        '# Strategy',
        '',
        '**Horizon**   ',
        `**Written** ${date}`,
        '',
        '## Where we are now',
        '',
        'An honest read. A strategy built on a flattering diagnosis fails at the diagnosis.',
        '',
        '## Where we are going',
        '',
        '## The choices that get us there',
        '',
        '| Choice | Instead of | Because |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## What we will not do',
        '',
        '## How we will know',
        '',
        '| Measure | Today | In 12 months |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## What has to be true',
        '',
        '## Review',
        '',
        'When we come back to this, and what would make us change it.',
        '',
      ].join('\n'),
    },
    {
      id: 'employee-onboarding',
      title: 'Employee onboarding',
      summary: 'A new joiner\'s first two weeks, with an owner against every line.',
      category: 'People',
      kind: 'document',
      icon: 'star',
      body: [
        '# Onboarding',
        '',
        '**Joining**   ',
        '**Role**   ',
        '**Start date**   ',
        '**Manager**   ',
        '**Buddy**   ',
        '',
        '## Before day one',
        '',
        '- [ ] Accounts and access requested',
        '- [ ] Equipment ordered',
        '- [ ] First-week calendar sent',
        '',
        '## Day one',
        '',
        '- [ ] Welcome and introductions',
        '- [ ] Tools and accounts working',
        '- [ ] Handbook and policies',
        '',
        '## Week one',
        '',
        '- [ ] Meet the team, one to one',
        '- [ ] Read: ',
        '- [ ] First small piece of real work',
        '',
        '## Week two',
        '',
        '- [ ] Owns something end to end',
        '- [ ] Check-in with manager',
        '',
        '## 30 / 60 / 90',
        '',
        '| By | What good looks like |',
        '| --- | --- |',
        '| 30 days |  |',
        '| 60 days |  |',
        '| 90 days |  |',
        '',
      ].join('\n'),
    },
    {
      id: 'performance-review',
      title: 'Performance review',
      summary: 'Evidence, then judgement, then what changes next quarter.',
      category: 'People',
      kind: 'document',
      icon: 'star',
      body: [
        '# Performance review',
        '',
        '**Employee**   ',
        '**Reviewer**   ',
        '**Period**   ',
        `**Date** ${date}`,
        '',
        '## What they were working towards',
        '',
        '| Goal | Agreed | Outcome |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## What went well',
        '',
        'With examples. A review without examples is an opinion.',
        '',
        '## What did not',
        '',
        '## How they work with others',
        '',
        '## Their own view',
        '',
        '## Agreed for next period',
        '',
        '| Goal | Measure | By when |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## Support they need',
        '',
      ].join('\n'),
    },
    {
      id: 'contract-review',
      title: 'Contract review',
      summary: 'The clauses that carry risk, flagged against a position.',
      category: 'Operations',
      kind: 'document',
      icon: 'code',
      body: [
        '# Contract review',
        '',
        '**Counterparty**   ',
        '**Agreement**   ',
        '**Value**   ',
        '**Term**   ',
        `**Reviewed** ${date}  `,
        '**Reviewer**   ',
        '',
        '## Summary position',
        '',
        'Sign / sign with amendments / do not sign, and why, in three lines.',
        '',
        '## Commercial terms',
        '',
        '| Term | What it says | Our position |',
        '| --- | --- | --- |',
        '| Price |  |  |',
        '| Payment terms |  |  |',
        '| Term and renewal |  |  |',
        '',
        '## Risk clauses',
        '',
        '| Clause | Risk | Acceptable? | Proposed change |',
        '| --- | --- | --- | --- |',
        '| Liability cap |  |  |  |',
        '| Indemnities |  |  |  |',
        '| Termination |  |  |  |',
        '| IP ownership |  |  |  |',
        '| Data protection |  |  |  |',
        '',
        '## Obligations we take on',
        '',
        'What the business has to actually do, and who will do it.',
        '',
        '## Recommendation',
        '',
      ].join('\n'),
    },
    {
      id: 'research',
      title: 'Research notes',
      summary: 'A question, the evidence found, and what it does not answer.',
      category: 'Strategy',
      kind: 'document',
      icon: 'lightbulb',
      body: [
        '# Research notes',
        '',
        '**Question**   ',
        `**Started** ${date}`,
        '',
        '## Why we are asking',
        '',
        '## What we found',
        '',
        '## Sources',
        '',
        '| Source | Date | What it supports |',
        '| --- | --- | --- |',
        '|  |  |  |',
        '',
        '## What this does not answer',
        '',
        '## So what',
        '',
        'The decision this changes. Research that changes no decision is a hobby.',
        '',
      ].join('\n'),
    },

    // -- Spreadsheets --------------------------------------------------------

    {
      id: 'budget',
      title: 'Annual budget',
      summary: 'Planned against actual by line, with the variance calculated.',
      category: 'Planning',
      kind: 'sheet',
      icon: 'table',
      body: '',
      columns: [
        { name: 'Line', type: 'text', width: 220 },
        { name: 'Category', type: 'select', width: 150,
          options: ['People', 'Software', 'Marketing', 'Facilities', 'Travel', 'Other'] },
        { name: 'Owner', type: 'member', width: 170 },
        { name: 'Budget', type: 'currency', width: 140, aggregate: 'sum' },
        { name: 'Actual', type: 'currency', width: 140, aggregate: 'sum' },
        { name: 'Variance', type: 'currency', width: 140, aggregate: 'sum', formula: '=Budget - Actual' },
      ],
    },
    {
      id: 'forecast',
      title: 'Revenue forecast',
      summary: 'Weighted pipeline by quarter, with the expected value computed.',
      category: 'Planning',
      kind: 'sheet',
      icon: 'table',
      body: '',
      columns: [
        { name: 'Opportunity', type: 'text', width: 240 },
        { name: 'Owner', type: 'member', width: 170 },
        { name: 'Quarter', type: 'select', width: 120, options: ['Q1', 'Q2', 'Q3', 'Q4'] },
        { name: 'Value', type: 'currency', width: 140, aggregate: 'sum' },
        { name: 'Confidence', type: 'number', width: 120, align: 'right' },
        { name: 'Weighted', type: 'currency', width: 140, aggregate: 'sum', formula: '=Value * Confidence / 100' },
        { name: 'Close date', type: 'date', width: 130 },
      ],
    },
    {
      id: 'project-plan',
      title: 'Project plan',
      summary: 'Tasks, owners, dates and status in one grid.',
      category: 'Planning',
      kind: 'sheet',
      icon: 'table',
      body: '',
      columns: [
        { name: 'Task', type: 'text', width: 260 },
        { name: 'Phase', type: 'text', width: 150 },
        { name: 'Owner', type: 'member', width: 170 },
        { name: 'Status', type: 'select', width: 140,
          options: ['Not started', 'In progress', 'Blocked', 'Done'] },
        { name: 'Start', type: 'date', width: 130 },
        { name: 'Due', type: 'date', width: 130 },
        { name: 'Days', type: 'number', width: 90, align: 'right', aggregate: 'sum' },
        { name: 'Done', type: 'checkbox', width: 80 },
      ],
    },
    {
      id: 'inventory-plan',
      title: 'Stock plan',
      summary: 'What we hold, what it is worth, and when to reorder.',
      category: 'Planning',
      kind: 'sheet',
      icon: 'table',
      body: '',
      columns: [
        { name: 'Item', type: 'text', width: 240 },
        { name: 'SKU', type: 'text', width: 130 },
        { name: 'On hand', type: 'number', width: 110, align: 'right', aggregate: 'sum' },
        { name: 'Reorder at', type: 'number', width: 110, align: 'right' },
        { name: 'Unit cost', type: 'currency', width: 130 },
        { name: 'Value', type: 'currency', width: 140, aggregate: 'sum', formula: '=On hand * Unit cost' },
        { name: 'Supplier', type: 'text', width: 170 },
      ],
    },
  ];
}

/** One template by id, or null. Used by the create-from-template endpoint. */
export function builtInTemplate(id: string): WorkspaceTemplate | null {
  return builtInTemplates().find(t => t.id === id) ?? null;
}
