-- ═══════════════════════════════════════════════════════════════════════════
--  0017 — Finishing the workspace, the communication module, and the settings
--         that were stored but never read
-- ═══════════════════════════════════════════════════════════════════════════
--
--  Three modules were structurally incomplete rather than merely unpolished.
--  Each one had a screen, and behind the screen either nothing to write to or
--  a rule that could not be expressed.
--
--  1. WORKSPACE. `workspace_pages` is a tree of markdown documents and that is
--     all it can hold. The module's own header offers "Document / Spreadsheet
--     / File Vault", but there is no table for a spreadsheet and no table row
--     for an uploaded file, so two of the three tabs rendered fixed sample
--     data and lost everything on reload. Sharing was a button that raised a
--     toast: every page in the organisation was readable by every employee,
--     with no way to say otherwise, which is not a workspace anyone can put
--     an HR folder in.
--
--  2. COMMUNICATION. Channels could be listed and posted to, and nothing else.
--     There was no way to create one, no way to add or remove anybody, and —
--     worse — `channels_select` was generated by the same loop as `companies`
--     and `products`, so it granted SELECT on every row in the organisation.
--     A private channel's messages were protected; its name, topic and
--     existence were not, and a direct message between two colleagues was
--     listed in everybody's sidebar. Sections 4 and 5 below make the channel
--     row as private as its contents, and give a channel an owner, a joining
--     rule and a posting rule.
--
--  3. SETTINGS. `organizations.work_days` is read by the leave logic but not
--     by the register's expected-days figure; `org_settings` holds three keys
--     seeded in 0008 and nothing reads two of them. Section 6 adds the
--     remaining policy keys and backfills them, so the administration screen
--     has a real store behind every control it offers.
--
--  Everything here is additive: no column is dropped, no default changes, and
--  each new table is empty until something writes to it. The two policies that
--  are replaced (`channels_select`, `channel_members_write`) are replaced with
--  strictly narrower ones — nobody loses access to a channel they are in.
-- ═══════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────
--  1. Workspace pages: what kind of page, and who may see it
-- ───────────────────────────────────────────────────────────────────────────
--
--  `kind` distinguishes a document from a spreadsheet. Both are pages — they
--  share a title, an icon, a place in the tree, a version history and a
--  sharing rule — so giving spreadsheets their own top-level table would mean
--  duplicating all of that and then keeping the two copies in step. What
--  differs is only where the body lives: a document's is `content`, a
--  spreadsheet's is the column and row tables in section 2.
--
--  `visibility` defaults to 'organization', which is exactly the behaviour
--  every existing page already has. Nothing changes for anything already
--  stored; the other values are opt-in.

ALTER TABLE workspace_pages
  ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'document',
  ADD COLUMN IF NOT EXISTS visibility text NOT NULL DEFAULT 'organization',
  ADD COLUMN IF NOT EXISTS department_id uuid REFERENCES departments(id) ON DELETE SET NULL,
  /**
   * Version counter, maintained by the snapshot trigger in section 3.
   *
   * Held on the page rather than derived with max(version) so concurrent
   * edits cannot both compute the same next number and collide on the
   * unique key.
   */
  ADD COLUMN IF NOT EXISTS version int NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pages_kind_valid') THEN
    ALTER TABLE workspace_pages ADD CONSTRAINT pages_kind_valid
      CHECK (kind IN ('document', 'sheet'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pages_visibility_valid') THEN
    ALTER TABLE workspace_pages ADD CONSTRAINT pages_visibility_valid
      CHECK (visibility IN ('inherit', 'organization', 'department', 'private'));
  END IF;
END $$;

COMMENT ON COLUMN workspace_pages.visibility IS
  'inherit = take the parent folder''s rule (the default for anything created '
  'inside a restricted folder); organization = every employee; department = '
  'the named department; private = the owner plus explicit shares.';

/**
 * A folder cannot contain itself.
 *
 * Moving a folder into its own descendant is the one destructive mistake the
 * tree UI makes easy — drag "Marketing" into "Marketing / Campaigns" and the
 * whole subtree detaches from the root and becomes unreachable, while every
 * recursive read spins. Rejected at the database because the move endpoint is
 * not the only thing that can write `parent_id`.
 */
CREATE OR REPLACE FUNCTION public.prevent_page_cycle()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  ancestor uuid := NEW.parent_id;
  hops     int  := 0;
BEGIN
  IF NEW.parent_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.parent_id = NEW.id THEN
    RAISE EXCEPTION 'A folder cannot be placed inside itself.'
      USING ERRCODE = 'check_violation';
  END IF;

  WHILE ancestor IS NOT NULL AND hops < 100 LOOP
    IF ancestor = NEW.id THEN
      RAISE EXCEPTION 'A folder cannot be moved inside one of its own subfolders.'
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT parent_id INTO ancestor FROM workspace_pages WHERE id = ancestor;
    hops := hops + 1;
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_page_cycle ON workspace_pages;
CREATE TRIGGER trg_prevent_page_cycle
  BEFORE INSERT OR UPDATE OF parent_id ON workspace_pages
  FOR EACH ROW EXECUTE FUNCTION public.prevent_page_cycle();

-- ── Explicit shares ────────────────────────────────────────────────────────
--
--  A share names either a person or a department, never both. Two nullable
--  columns with a CHECK rather than two tables, because every read wants them
--  together — "may this person open this folder" is one question.

CREATE TABLE IF NOT EXISTS workspace_page_shares (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  page_id         uuid NOT NULL REFERENCES workspace_pages(id) ON DELETE CASCADE,
  member_id       uuid REFERENCES organization_members(id) ON DELETE CASCADE,
  department_id   uuid REFERENCES departments(id) ON DELETE CASCADE,
  /**
   * view   — open and read, including everything inside a shared folder
   * edit   — change the body, add pages inside a shared folder
   * manage — the above plus re-sharing and deleting
   */
  permission      text NOT NULL DEFAULT 'view'
                  CHECK (permission IN ('view', 'edit', 'manage')),
  granted_by      uuid REFERENCES organization_members(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT share_has_exactly_one_subject
    CHECK ((member_id IS NULL) <> (department_id IS NULL))
);

-- Two shares of the same page to the same subject would make "what may they
-- do" ambiguous. Partial uniques because NULL is not equal to NULL.
CREATE UNIQUE INDEX IF NOT EXISTS uq_page_share_member
  ON workspace_page_shares (page_id, member_id) WHERE member_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_page_share_department
  ON workspace_page_shares (page_id, department_id) WHERE department_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_page_shares_page ON workspace_page_shares (page_id);

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  The effective permission a caller holds on a page.
 * ═══════════════════════════════════════════════════════════════════════════
 *
 *  ── Why this takes the row's columns rather than just its id ─────────────
 *
 *  The obvious signature is `page_permission(page uuid)`, looking the row up
 *  itself. That version cannot be used in the row-level policies, and the
 *  reason is worth writing down because the failure is silent and confusing.
 *
 *  A `STABLE` function sees the snapshot taken at the start of the statement.
 *  During `INSERT ... RETURNING`, Postgres applies the SELECT policy to the
 *  new row — but a STABLE function called from that policy cannot see the row
 *  the statement is in the middle of inserting. It looks it up, finds nothing,
 *  and returns NULL. The policy then reads that as "no access" and the insert
 *  fails with 42501, *new row violates row-level security policy* — for a row
 *  the caller had every right to create. Every workspace create returned 403.
 *
 *  Marking it VOLATILE would fix the visibility and cost a fresh snapshot per
 *  row, on a tree query that touches every page in the workspace.
 *
 *  So the policies pass the columns they already have in hand. Only the walk
 *  up the ancestry needs a lookup, and an ancestor is always a committed row.
 *
 *  Returns NULL when the caller has no access at all. Administrators and the
 *  page's own creator always resolve 'manage' — an owner locking themselves
 *  out of their own folder is not a security property, it is a support ticket.
 */
CREATE OR REPLACE FUNCTION public.page_grant(
  org     uuid,
  vis     text,
  dept    uuid,
  creator uuid,
  parent  uuid,
  page    uuid
)
RETURNS text
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  me      uuid;
  my_dept uuid;
  granted text;
BEGIN
  IF org IS NULL THEN RETURN NULL; END IF;

  IF NOT public.can_access_module(org, 'workspace') THEN
    RETURN NULL;
  END IF;

  IF public.is_org_admin(org) THEN RETURN 'manage'; END IF;

  me      := public.auth_member_id(org);
  my_dept := public.auth_department_id(org);

  IF creator IS NOT NULL AND creator = me THEN
    RETURN 'manage';
  END IF;

  -- An explicit share on this page. Empty for a row being inserted, which is
  -- correct: nothing can have been shared with anybody yet.
  SELECT s.permission INTO granted
  FROM workspace_page_shares s
  WHERE s.page_id = page
    AND (s.member_id = me OR (s.department_id IS NOT NULL AND s.department_id = my_dept))
  -- The most generous share wins when somebody is named both directly and
  -- through their department.
  ORDER BY CASE s.permission WHEN 'manage' THEN 3 WHEN 'edit' THEN 2 ELSE 1 END DESC
  LIMIT 1;

  IF granted IS NOT NULL THEN RETURN granted; END IF;

  IF vis = 'organization' THEN
    RETURN 'edit';
  ELSIF vis = 'department' THEN
    IF my_dept IS NOT NULL AND dept = my_dept THEN RETURN 'edit'; END IF;
    RETURN NULL;
  ELSIF vis = 'private' THEN
    RETURN NULL;
  END IF;

  -- 'inherit': take the parent folder's answer. A page that inherits all the
  -- way to the root with nothing decided is a normal organisation-visible page.
  IF parent IS NULL THEN RETURN 'edit'; END IF;
  RETURN public.page_permission(parent);
END;
$$;

/**
 * The same question, for a page that is already stored.
 *
 * This is what the view and the endpoints call — they have an id and want the
 * answer. It looks the row up and delegates, so there is exactly one
 * description of the rule.
 */
CREATE OR REPLACE FUNCTION public.page_permission(page uuid)
RETURNS text
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  cur workspace_pages;
BEGIN
  SELECT * INTO cur FROM workspace_pages WHERE id = page;
  IF NOT FOUND THEN RETURN NULL; END IF;

  RETURN public.page_grant(
    cur.organization_id, cur.visibility, cur.department_id,
    cur.created_by, cur.parent_id, cur.id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.page_permission(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.page_grant(uuid, text, uuid, uuid, uuid, uuid) TO authenticated;

ALTER TABLE workspace_page_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_page_shares FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS page_shares_select ON workspace_page_shares;
CREATE POLICY page_shares_select ON workspace_page_shares FOR SELECT TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) IS NOT NULL);

-- Only someone who could re-share may create or revoke a share.
DROP POLICY IF EXISTS page_shares_write ON workspace_page_shares;
CREATE POLICY page_shares_write ON workspace_page_shares FOR ALL TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) = 'manage')
  WITH CHECK (organization_id = ANY (public.auth_org_ids())
              AND public.page_permission(page_id) = 'manage');

-- ── Page policies, replaced to honour visibility ───────────────────────────
--
--  The generated policies in 0005 granted every employee full read and write
--  on every page. These keep that outcome for organisation-visible pages —
--  which is all of them today — and enforce the new rules for the rest.

--
--  Every policy below passes the row's own columns to `page_grant()` rather
--  than asking `page_permission(id)` to look them up. See the comment on
--  `page_grant` — a STABLE lookup cannot see the row an INSERT is in the
--  middle of writing, and `INSERT ... RETURNING` applies the SELECT policy to
--  exactly that row.

DROP POLICY IF EXISTS workspace_pages_select ON workspace_pages;
CREATE POLICY workspace_pages_select ON workspace_pages FOR SELECT TO authenticated
  USING (
    organization_id = ANY (public.auth_org_ids())
    AND public.page_grant(organization_id, visibility, department_id,
                          created_by, parent_id, id) IS NOT NULL
  );

DROP POLICY IF EXISTS workspace_pages_insert ON workspace_pages;
CREATE POLICY workspace_pages_insert ON workspace_pages FOR INSERT TO authenticated
  WITH CHECK (
    organization_id = ANY (public.auth_org_ids())
    AND public.can_access_module(organization_id, 'workspace')
    -- Creating inside a folder requires the right to write in that folder.
    AND (parent_id IS NULL OR public.page_permission(parent_id) IN ('edit', 'manage'))
  );

DROP POLICY IF EXISTS workspace_pages_update ON workspace_pages;
CREATE POLICY workspace_pages_update ON workspace_pages FOR UPDATE TO authenticated
  USING (
    organization_id = ANY (public.auth_org_ids())
    AND public.page_grant(organization_id, visibility, department_id,
                          created_by, parent_id, id) IN ('edit', 'manage')
  )
  WITH CHECK (organization_id = ANY (public.auth_org_ids()));

/**
 * Deletion is narrower than editing.
 *
 * 0005 allowed any manager to delete any page in the organisation. A page you
 * cannot even open should not be one you can destroy, so this asks for
 * 'manage' — which administrators, the creator, and anyone explicitly granted
 * it all hold.
 */
DROP POLICY IF EXISTS workspace_pages_delete ON workspace_pages;
CREATE POLICY workspace_pages_delete ON workspace_pages FOR DELETE TO authenticated
  USING (
    organization_id = ANY (public.auth_org_ids())
    AND public.page_grant(organization_id, visibility, department_id,
                          created_by, parent_id, id) = 'manage'
  );


-- ───────────────────────────────────────────────────────────────────────────
--  2. Spreadsheets
-- ───────────────────────────────────────────────────────────────────────────
--
--  A column table and a row table, with the cells held as jsonb keyed by
--  column id.
--
--  The alternative — a `cells` table with one row per cell — is the textbook
--  answer and the wrong one here: a 40-column, 500-row sheet becomes 20,000
--  rows to read, order and reassemble on every open, and every column rename
--  is a mass update. Keying the jsonb by column id rather than by column name
--  is what makes renaming a column free and makes deleting one leave no
--  dangling references that a reader can see.
--
--  Column definitions stay relational because they are what the UI enumerates,
--  what validation reads, and what has to keep a stable order.

CREATE TABLE IF NOT EXISTS workspace_sheet_columns (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  page_id         uuid NOT NULL REFERENCES workspace_pages(id) ON DELETE CASCADE,
  name            text NOT NULL CHECK (btrim(name) <> ''),
  /**
   * The cell editor to render and how to sort the column.
   *
   * 'select' carries its choices in `options`; 'currency' formats with the
   * organisation's currency, so a finance sheet does not have to repeat the
   * symbol in every cell.
   */
  type            text NOT NULL DEFAULT 'text'
                  CHECK (type IN ('text','number','currency','date','select','checkbox','member','url')),
  options         jsonb NOT NULL DEFAULT '[]'::jsonb,
  width           int NOT NULL DEFAULT 180 CHECK (width BETWEEN 60 AND 900),
  position        int NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sheet_columns_page
  ON workspace_sheet_columns (page_id, position);

CREATE TABLE IF NOT EXISTS workspace_sheet_rows (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  page_id         uuid NOT NULL REFERENCES workspace_pages(id) ON DELETE CASCADE,
  /** { "<column uuid>": <value> } — absent key means an empty cell. */
  cells           jsonb NOT NULL DEFAULT '{}'::jsonb,
  position        int NOT NULL DEFAULT 0,
  created_by      uuid REFERENCES organization_members(id) ON DELETE SET NULL,
  updated_by      uuid REFERENCES organization_members(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sheet_rows_page
  ON workspace_sheet_rows (page_id, position);

/**
 * Dropping a column removes its cells.
 *
 * Without this the jsonb keeps the deleted column's values forever: invisible,
 * exported anyway, and reinstated the moment somebody re-adds a column that
 * happens to reuse the id. Cheap because it touches only the sheet concerned.
 */
CREATE OR REPLACE FUNCTION public.prune_sheet_column()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE workspace_sheet_rows
     SET cells = cells - OLD.id::text
   WHERE page_id = OLD.page_id
     AND cells ? OLD.id::text;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_prune_sheet_column ON workspace_sheet_columns;
CREATE TRIGGER trg_prune_sheet_column
  AFTER DELETE ON workspace_sheet_columns
  FOR EACH ROW EXECUTE FUNCTION public.prune_sheet_column();

-- Both tables inherit the page's sharing rule rather than restating it, so a
-- folder shared with HR carries its spreadsheets with it.
ALTER TABLE workspace_sheet_columns ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_sheet_columns FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_sheet_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_sheet_rows FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sheet_columns_select ON workspace_sheet_columns;
CREATE POLICY sheet_columns_select ON workspace_sheet_columns FOR SELECT TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) IS NOT NULL);

DROP POLICY IF EXISTS sheet_columns_write ON workspace_sheet_columns;
CREATE POLICY sheet_columns_write ON workspace_sheet_columns FOR ALL TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) IN ('edit', 'manage'))
  WITH CHECK (organization_id = ANY (public.auth_org_ids())
              AND public.page_permission(page_id) IN ('edit', 'manage'));

DROP POLICY IF EXISTS sheet_rows_select ON workspace_sheet_rows;
CREATE POLICY sheet_rows_select ON workspace_sheet_rows FOR SELECT TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) IS NOT NULL);

DROP POLICY IF EXISTS sheet_rows_write ON workspace_sheet_rows;
CREATE POLICY sheet_rows_write ON workspace_sheet_rows FOR ALL TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.page_permission(page_id) IN ('edit', 'manage'))
  WITH CHECK (organization_id = ANY (public.auth_org_ids())
              AND public.page_permission(page_id) IN ('edit', 'manage'));


-- ───────────────────────────────────────────────────────────────────────────
--  3. Document history
-- ───────────────────────────────────────────────────────────────────────────
--
--  `workspace_page_versions` has existed since 0003 and has never had a row
--  written to it, so "track document history" had a table and no history. A
--  trigger rather than an endpoint, because the page is edited from the
--  document view, the rename control and the move dialog, and a snapshot that
--  three call sites have to remember to take is one that eventually is not.
--
--  The snapshot records the state *before* the edit, which is what "restore"
--  needs — a history whose newest entry is identical to the live page is a
--  list of duplicates.

CREATE OR REPLACE FUNCTION public.snapshot_page_version()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Only substantive changes. Starring a page, moving it, or touching
  -- `updated_at` is not a revision anybody wants to scroll past.
  IF NEW.content IS NOT DISTINCT FROM OLD.content
     AND NEW.title IS NOT DISTINCT FROM OLD.title THEN
    RETURN NEW;
  END IF;

  INSERT INTO workspace_page_versions (page_id, content, title, version, edited_by)
  VALUES (OLD.id, OLD.content, OLD.title, OLD.version, OLD.last_edited_by)
  ON CONFLICT (page_id, version) DO NOTHING;

  NEW.version := OLD.version + 1;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_snapshot_page_version ON workspace_pages;
CREATE TRIGGER trg_snapshot_page_version
  BEFORE UPDATE ON workspace_pages
  FOR EACH ROW EXECUTE FUNCTION public.snapshot_page_version();

/**
 * History is pruned to the last fifty revisions per page.
 *
 * A document edited all day otherwise accumulates thousands of rows nobody
 * will ever open, and the version list becomes unusable long before the
 * storage matters.
 */
CREATE OR REPLACE FUNCTION public.prune_page_versions()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  DELETE FROM workspace_page_versions
  WHERE page_id = NEW.page_id
    AND id NOT IN (
      SELECT id FROM workspace_page_versions
      WHERE page_id = NEW.page_id
      ORDER BY version DESC
      LIMIT 50
    );
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_prune_page_versions ON workspace_page_versions;
CREATE TRIGGER trg_prune_page_versions
  AFTER INSERT ON workspace_page_versions
  FOR EACH ROW EXECUTE FUNCTION public.prune_page_versions();

-- The versions table is scoped through its page, which now carries a sharing
-- rule; 0005 scoped it to the whole organisation.
DROP POLICY IF EXISTS page_versions_select ON workspace_page_versions;
CREATE POLICY page_versions_select ON workspace_page_versions FOR SELECT TO authenticated
  USING (public.page_permission(page_id) IS NOT NULL);

DROP POLICY IF EXISTS page_versions_insert ON workspace_page_versions;
CREATE POLICY page_versions_insert ON workspace_page_versions FOR INSERT TO authenticated
  WITH CHECK (public.page_permission(page_id) IN ('edit', 'manage'));


-- ───────────────────────────────────────────────────────────────────────────
--  4. Files
-- ───────────────────────────────────────────────────────────────────────────
--
--  `files` has held metadata for Supabase Storage objects since 0003 and the
--  application has never written to it: the uploader in the workspace made an
--  object URL in the browser, showed a progress bar driven by setInterval, and
--  reported success. Nothing left the tab. These columns are what a file
--  browser needs on top of what was already there.

ALTER TABLE files
  ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '',
  /** Superseded uploads keep their row; the newest version wins the listing. */
  ADD COLUMN IF NOT EXISTS version int NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_files_page ON files (page_id) WHERE deleted_at IS NULL;

/**
 * Renaming and moving a file is an update, and there was no UPDATE policy.
 *
 * 0005 gave `files` select, insert and delete only, so a rename silently
 * affected zero rows and the endpoint answered 200. Restricted to the uploader
 * and administrators, matching the delete rule.
 */
DROP POLICY IF EXISTS files_update ON files;
CREATE POLICY files_update ON files FOR UPDATE TO authenticated
  USING (
    organization_id = ANY (public.auth_org_ids())
    AND (uploaded_by = public.auth_member_id(organization_id)
         OR public.is_org_admin(organization_id))
  )
  WITH CHECK (organization_id = ANY (public.auth_org_ids()));


-- ───────────────────────────────────────────────────────────────────────────
--  5. Communication
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE channels
  /**
   * The human name, separate from `name`.
   *
   * `name` is slugged on write so "#General" and "#general" cannot become two
   * channels — right for a channel, wrong for a group called "Q3 Launch Team",
   * which came back as "q3-launch-team" and was title-cased on the way out.
   */
  ADD COLUMN IF NOT EXISTS display_name text,
  ADD COLUMN IF NOT EXISTS topic text NOT NULL DEFAULT '',
  /** Who may post. An announcement channel is one where this is 'admins'. */
  ADD COLUMN IF NOT EXISTS post_policy text NOT NULL DEFAULT 'everyone',
  /** Whether an employee may add themselves, or must be added. */
  ADD COLUMN IF NOT EXISTS join_policy text NOT NULL DEFAULT 'open';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'channels_post_policy_valid') THEN
    ALTER TABLE channels ADD CONSTRAINT channels_post_policy_valid
      CHECK (post_policy IN ('everyone', 'members', 'admins'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'channels_join_policy_valid') THEN
    ALTER TABLE channels ADD CONSTRAINT channels_join_policy_valid
      CHECK (join_policy IN ('open', 'invite'));
  END IF;
END $$;

-- Existing announcement channels described their posting rule through their
-- type and had no column to say so.
UPDATE channels SET post_policy = 'admins'
 WHERE type = 'announcement' AND post_policy = 'everyone';

UPDATE channels SET join_policy = 'invite'
 WHERE type IN ('private', 'direct') AND join_policy = 'open';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'channel_members_role_valid') THEN
    ALTER TABLE channel_members ADD CONSTRAINT channel_members_role_valid
      CHECK (role IN ('owner', 'admin', 'member'));
  END IF;
END $$;

/** Is the caller a member of this channel? */
CREATE OR REPLACE FUNCTION public.is_channel_member(chan uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM channel_members cm
    JOIN channels c ON c.id = cm.channel_id
    WHERE cm.channel_id = chan
      AND cm.member_id = public.auth_member_id(c.organization_id)
  );
$$;

/** Does the caller administer this channel — its owner, a channel admin, or an org admin? */
CREATE OR REPLACE FUNCTION public.is_channel_admin(chan uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM channels c
    WHERE c.id = chan
      AND (
        public.is_org_admin(c.organization_id)
        OR c.created_by = public.auth_member_id(c.organization_id)
        OR EXISTS (
          SELECT 1 FROM channel_members cm
          WHERE cm.channel_id = c.id
            AND cm.member_id = public.auth_member_id(c.organization_id)
            AND cm.role IN ('owner', 'admin')
        )
      )
  );
$$;

/** May the caller post here? Reads `post_policy`, which the admin screen sets. */
CREATE OR REPLACE FUNCTION public.can_post_to_channel(chan uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM channels c
    WHERE c.id = chan
      AND c.is_archived = false
      AND public.can_access_module(c.organization_id, 'communication')
      AND CASE c.post_policy
            WHEN 'everyone' THEN
              c.type IN ('public') OR public.is_channel_member(c.id)
            WHEN 'members'  THEN public.is_channel_member(c.id)
            ELSE                 public.is_channel_admin(c.id)
          END
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_channel_member(uuid)    TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_channel_admin(uuid)     TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_post_to_channel(uuid)  TO authenticated;

/**
 * A private channel's existence is private too.
 *
 * The generated policy in 0005 exposed every channel row to every employee.
 * Messages were protected, so nothing leaked from inside a conversation — but
 * a direct message between two people appeared in everyone's sidebar with
 * both participants' names in the slug, and a private HR channel announced
 * itself by title. This is the narrowing that fixes it.
 */
DROP POLICY IF EXISTS channels_select ON channels;
CREATE POLICY channels_select ON channels FOR SELECT TO authenticated
  USING (
    organization_id = ANY (public.auth_org_ids())
    AND public.can_access_module(organization_id, 'communication')
    AND (
      type IN ('public', 'announcement')
      OR public.is_channel_member(id)
      OR public.is_org_admin(organization_id)
    )
  );

DROP POLICY IF EXISTS channels_update ON channels;
CREATE POLICY channels_update ON channels FOR UPDATE TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.is_channel_admin(id))
  WITH CHECK (organization_id = ANY (public.auth_org_ids()));

DROP POLICY IF EXISTS channels_delete ON channels;
CREATE POLICY channels_delete ON channels FOR DELETE TO authenticated
  USING (organization_id = ANY (public.auth_org_ids())
         AND public.is_channel_admin(id));

/**
 * Membership, split by verb.
 *
 * 0005 had a single FOR ALL policy whose only condition was "the channel is in
 * an organisation you belong to" — so any employee could add themselves to the
 * leadership channel, or remove anybody from anything. Splitting it lets each
 * verb carry its own rule:
 *
 *   insert — channel admins add anyone; an employee may add only themselves,
 *            and only to an open channel
 *   update — you maintain your own read marker and mute flag; admins may
 *            change roles
 *   delete — you may always leave; admins may remove others
 */
DROP POLICY IF EXISTS channel_members_write ON channel_members;

DROP POLICY IF EXISTS channel_members_insert ON channel_members;
CREATE POLICY channel_members_insert ON channel_members FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM channels c
      WHERE c.id = channel_id
        AND c.organization_id = ANY (public.auth_org_ids())
        AND public.can_access_module(c.organization_id, 'communication')
        AND (
          public.is_channel_admin(c.id)
          OR (member_id = public.auth_member_id(c.organization_id)
              AND c.join_policy = 'open'
              AND c.type IN ('public', 'announcement'))
        )
    )
  );

DROP POLICY IF EXISTS channel_members_update ON channel_members;
CREATE POLICY channel_members_update ON channel_members FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM channels c
      WHERE c.id = channel_id
        AND c.organization_id = ANY (public.auth_org_ids())
        AND (member_id = public.auth_member_id(c.organization_id)
             OR public.is_channel_admin(c.id))
    )
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM channels c
            WHERE c.id = channel_id AND c.organization_id = ANY (public.auth_org_ids()))
  );

DROP POLICY IF EXISTS channel_members_delete ON channel_members;
CREATE POLICY channel_members_delete ON channel_members FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM channels c
      WHERE c.id = channel_id
        AND c.organization_id = ANY (public.auth_org_ids())
        AND (member_id = public.auth_member_id(c.organization_id)
             OR public.is_channel_admin(c.id))
    )
  );

/**
 * Posting now respects the channel's rule.
 *
 * Previously any member of the organisation could insert a message into any
 * channel id they could guess, including a private one they were not in —
 * `messages_insert` checked only the tenant and the sender. Reading it back
 * was impossible, which limited the damage, but the message was still
 * delivered to everyone who *was* in the channel.
 */
DROP POLICY IF EXISTS messages_insert ON messages;
CREATE POLICY messages_insert ON messages FOR INSERT TO authenticated
  WITH CHECK (
    organization_id = ANY (public.auth_org_ids())
    AND sender_id = public.auth_member_id(organization_id)
    AND public.can_post_to_channel(channel_id)
  );

-- ── Direct messages ────────────────────────────────────────────────────────

/**
 * Open a direct conversation with a colleague, creating it if needed.
 *
 * An RPC rather than a POST that the client assembles, for two reasons: the
 * pair must be unique in both directions — otherwise Ada messaging Grace and
 * Grace messaging Ada produce two half-empty threads — and creating the
 * channel and both memberships has to be one atomic act, or a crash between
 * them leaves a conversation nobody is in.
 */
CREATE OR REPLACE FUNCTION public.open_direct_channel(org uuid, other_member uuid)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  me      uuid := public.auth_member_id(org);
  chan    uuid;
  slug    text;
BEGIN
  IF me IS NULL THEN
    RAISE EXCEPTION 'You are not a member of this organization.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF NOT public.can_access_module(org, 'communication') THEN
    RAISE EXCEPTION 'Your role does not have access to messaging.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF other_member = me THEN
    RAISE EXCEPTION 'You cannot start a conversation with yourself.'
      USING ERRCODE = 'check_violation';
  END IF;

  -- The other party must be a current employee of the same organisation. This
  -- is what stops a client login being pulled into an internal thread.
  IF NOT EXISTS (
    SELECT 1 FROM organization_members om
    WHERE om.id = other_member
      AND om.organization_id = org
      AND om.is_active = true
      AND om.role <> 'client'
  ) THEN
    RAISE EXCEPTION 'That person cannot be messaged.' USING ERRCODE = 'check_violation';
  END IF;

  -- Existing thread: a direct channel whose membership is exactly these two.
  SELECT c.id INTO chan
  FROM channels c
  WHERE c.organization_id = org
    AND c.type = 'direct'
    AND (SELECT COUNT(*) FROM channel_members cm WHERE cm.channel_id = c.id) = 2
    AND EXISTS (SELECT 1 FROM channel_members cm WHERE cm.channel_id = c.id AND cm.member_id = me)
    AND EXISTS (SELECT 1 FROM channel_members cm WHERE cm.channel_id = c.id AND cm.member_id = other_member)
  LIMIT 1;

  IF chan IS NOT NULL THEN
    RETURN chan;
  END IF;

  -- Deterministic, so two people opening the thread at the same moment cannot
  -- create two channels with different names.
  slug := 'dm-' || LEAST(me::text, other_member::text) || '-' || GREATEST(me::text, other_member::text);

  INSERT INTO channels (organization_id, name, display_name, description, type,
                        created_by, join_policy, post_policy)
  VALUES (org, slug, NULL, '', 'direct', me, 'invite', 'members')
  RETURNING id INTO chan;

  INSERT INTO channel_members (channel_id, member_id, role)
  VALUES (chan, me, 'owner'), (chan, other_member, 'member')
  ON CONFLICT (channel_id, member_id) DO NOTHING;

  RETURN chan;
END;
$$;

GRANT EXECUTE ON FUNCTION public.open_direct_channel(uuid, uuid) TO authenticated;

/**
 * Everything the sidebar needs, in one query.
 *
 * The module was fetching the channel list and then one request per channel to
 * find its last message — twenty channels meant twenty-one round trips on
 * every load, and the unread badge was hard-coded to zero because there was
 * nothing to read it from. `last_read_at` on the membership has been the right
 * source since 0003; this is the query that finally uses it.
 */
CREATE OR REPLACE FUNCTION public.channel_overview(org uuid)
RETURNS TABLE (
  channel_id      uuid,
  name            text,
  display_name    text,
  description     text,
  topic           text,
  type            channel_type,
  post_policy     text,
  join_policy     text,
  is_archived     boolean,
  created_by      uuid,
  member_count    int,
  message_count   int,
  unread_count    int,
  is_member       boolean,
  is_admin        boolean,
  my_role         text,
  last_message    text,
  last_message_at timestamptz,
  last_sender     text,
  counterpart_id   uuid,
  counterpart_name text,
  counterpart_avatar text
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH me AS (SELECT public.auth_member_id(org) AS id),
  visible AS (
    SELECT c.*
    FROM channels c, me
    WHERE c.organization_id = org
      AND public.can_access_module(org, 'communication')
      AND (
        c.type IN ('public', 'announcement')
        OR EXISTS (SELECT 1 FROM channel_members cm
                   WHERE cm.channel_id = c.id AND cm.member_id = me.id)
        OR public.is_org_admin(org)
      )
  )
  SELECT
    v.id,
    v.name,
    v.display_name,
    v.description,
    v.topic,
    v.type,
    v.post_policy,
    v.join_policy,
    v.is_archived,
    v.created_by,
    (SELECT COUNT(*)::int FROM channel_members cm WHERE cm.channel_id = v.id),
    (SELECT COUNT(*)::int FROM messages m WHERE m.channel_id = v.id AND m.deleted_at IS NULL),
    (SELECT COUNT(*)::int FROM messages m
      WHERE m.channel_id = v.id
        AND m.deleted_at IS NULL
        AND m.sender_id IS DISTINCT FROM me.id
        AND m.created_at > COALESCE(
              (SELECT cm.last_read_at FROM channel_members cm
                WHERE cm.channel_id = v.id AND cm.member_id = me.id),
              '-infinity'::timestamptz)),
    EXISTS (SELECT 1 FROM channel_members cm
            WHERE cm.channel_id = v.id AND cm.member_id = me.id),
    public.is_channel_admin(v.id),
    (SELECT cm.role FROM channel_members cm
      WHERE cm.channel_id = v.id AND cm.member_id = me.id),
    last_msg.body,
    last_msg.created_at,
    last_msg.sender_name,
    -- For a direct message the sidebar shows the other person, not the slug.
    dm.member_id,
    dm.full_name,
    dm.avatar_url
  FROM visible v, me
  LEFT JOIN LATERAL (
    SELECT m.body, m.created_at, p.full_name AS sender_name
    FROM messages m
    LEFT JOIN organization_members om ON om.id = m.sender_id
    LEFT JOIN profiles p ON p.id = om.user_id
    WHERE m.channel_id = v.id AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC
    LIMIT 1
  ) last_msg ON true
  LEFT JOIN LATERAL (
    SELECT cm.member_id, p.full_name, p.avatar_url
    FROM channel_members cm
    JOIN organization_members om ON om.id = cm.member_id
    JOIN profiles p ON p.id = om.user_id
    WHERE v.type = 'direct'
      AND cm.channel_id = v.id
      AND cm.member_id IS DISTINCT FROM me.id
    LIMIT 1
  ) dm ON true
  ORDER BY COALESCE(last_msg.created_at, v.created_at) DESC;
$$;

GRANT EXECUTE ON FUNCTION public.channel_overview(uuid) TO authenticated;

/**
 * A new message notifies the people who are in the conversation.
 *
 * Direct messages and mentions only. Notifying every member of every channel
 * on every message is how a notification tray becomes something people learn
 * to ignore, and the unread badge already covers "there is something new in
 * this channel".
 */
CREATE OR REPLACE FUNCTION public.notify_message()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  chan      channels;
  audience  uuid[];
  who       text;
  label     text;
BEGIN
  SELECT * INTO chan FROM channels WHERE id = NEW.channel_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  SELECT p.full_name INTO who
  FROM organization_members om JOIN profiles p ON p.id = om.user_id
  WHERE om.id = NEW.sender_id;

  IF chan.type = 'direct' THEN
    SELECT COALESCE(array_agg(cm.member_id), ARRAY[]::uuid[]) INTO audience
    FROM channel_members cm WHERE cm.channel_id = chan.id;

    PERFORM public.notify_members(
      NEW.organization_id, audience, 'message',
      COALESCE(who, 'A colleague') || ' sent you a message',
      left(NEW.body, 140), 'channel', chan.id, '/dashboard?module=communication'
    );
  ELSIF array_length(NEW.mentions, 1) > 0 THEN
    label := COALESCE(NULLIF(chan.display_name, ''), '#' || chan.name);
    PERFORM public.notify_members(
      NEW.organization_id, NEW.mentions, 'mention',
      COALESCE(who, 'A colleague') || ' mentioned you in ' || label,
      left(NEW.body, 140), 'channel', chan.id, '/dashboard?module=communication'
    );
  END IF;

  RETURN NEW;
EXCEPTION WHEN others THEN
  -- A failed notification must never lose the message that caused it.
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_message ON messages;
CREATE TRIGGER trg_notify_message
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION public.notify_message();


-- ───────────────────────────────────────────────────────────────────────────
--  6. Settings that something actually reads
-- ───────────────────────────────────────────────────────────────────────────
--
--  0008 seeded three keys. The administration screen offers far more than
--  three settings, and the ones with no key behind them were being written
--  into the organisation's `settings` jsonb or dropped. These are the
--  remaining policy documents, with the shape the endpoints validate against.
--
--  Written for every existing organisation as well as new ones, so an
--  organisation created before this migration opens the settings screen fully
--  populated rather than blank.

CREATE OR REPLACE FUNCTION public.default_org_settings()
RETURNS jsonb
LANGUAGE sql IMMUTABLE
AS $$
  SELECT jsonb_build_object(
    'attendance_policy', jsonb_build_object(
      'allow_remote',        true,
      'require_note_remote', false,
      'half_day_minutes',    240,
      'auto_absent',         true,
      'overtime_after_minutes', 540
    ),
    'leave_policy', jsonb_build_object(
      -- Types the request form offers. Must be members of the `leave_type`
      -- enum; the endpoint rejects anything else rather than letting a typo
      -- reach a column that will refuse it later with 22P02.
      'types',              jsonb_build_array('vacation','sick','personal','maternity','paternity','bereavement','unpaid'),
      'requires_approval',  true,
      'min_notice_days',    0,
      'max_consecutive_days', 30,
      'allow_half_day',     true,
      'carry_over_days',    5
    ),
    'project_defaults', jsonb_build_object(
      'statuses',   jsonb_build_array('planning','active','on_hold','completed','cancelled','archived'),
      'priorities', jsonb_build_array('low','medium','high','critical'),
      'task_categories', jsonb_build_array('Feature','Bug','Improvement','Research','Documentation'),
      'milestone_stages', jsonb_build_array('planning','development','testing','review','deployment','completed'),
      'default_status',   'planning',
      'default_priority', 'medium',
      'templates', jsonb_build_array()
    ),
    /**
     * Which events produce a notification.
     *
     * Keyed by the *family* of the types the triggers actually emit —
     * `task` covers task_assigned, task_completed and task_blocked. A
     * settings screen whose labels do not correspond to anything the system
     * emits is how a toggle comes to control nothing, so these are matched
     * against the real vocabulary by `notification_enabled()` rather than
     * mapped through a translation table that would drift.
     */
    'notification_events', jsonb_build_object(
      'project',      true,
      'task',         true,
      'milestone',    true,
      'leave',        true,
      'invoice',      true,
      'expense',      true,
      'ticket',       true,
      'comment',      true,
      'mention',      true,
      'message',      true,
      'announcement', true,
      'channel',      true
    ),
    /**
     * Branding describes the tenant's *own* surfaces, not this platform's.
     *
     * The two keys here were `login_message` and `show_logo_in_sidebar`, which
     * named the platform's sign-in page and its navigation chrome — the
     * vocabulary of a white-label shell, in a product that is not one. Having
     * them here is what made rendering a customer's logo in place of this
     * product's name look like a completed feature. Renamed in 0021, which also
     * carries the stored values across.
     *
     * `primary_colour` accents their client portal and documents. The
     * platform's own accent is fixed in `lib/platform.ts` and is the same for
     * every customer.
     */
    'branding', jsonb_build_object(
      'primary_colour', '#10b981',
      'portal_welcome', '',
      'show_logo_in_portal', true
    )
  );
$$;

/**
 * Backfill, without overwriting anything an administrator has already set.
 *
 * `ON CONFLICT DO NOTHING` rather than an upsert: a key that already exists
 * holds a decision somebody made, and a migration that replaces it with the
 * default is a migration that silently reverses configuration.
 */
INSERT INTO org_settings (organization_id, key, value)
SELECT o.id, d.key, d.value
FROM organizations o
CROSS JOIN LATERAL jsonb_each(public.default_org_settings()) AS d(key, value)
ON CONFLICT (organization_id, key) DO NOTHING;

/**
 * New organisations get them too.
 *
 * `seed_new_organization` is replaced rather than extended because it is a
 * whole-function definition; the three keys it already wrote are reproduced
 * here unchanged, and everything else in the body is identical to 0008.
 */
CREATE OR REPLACE FUNCTION public.seed_new_organization()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO org_settings (organization_id, key, value) VALUES
    (NEW.id, 'leave_entitlement',
      '{"vacation": 25, "sick": 10, "personal": 3}'::jsonb),
    (NEW.id, 'invoice_defaults',
      '{"payment_terms_days": 30, "tax_rate": 0}'::jsonb),
    (NEW.id, 'notifications',
      '{"email_on_mention": true, "email_on_assignment": true}'::jsonb)
  ON CONFLICT DO NOTHING;

  INSERT INTO org_settings (organization_id, key, value)
  SELECT NEW.id, d.key, d.value
  FROM jsonb_each(public.default_org_settings()) AS d(key, value)
  ON CONFLICT DO NOTHING;

  INSERT INTO departments (organization_id, name, description)
  VALUES (NEW.id, 'General', 'Default department')
  ON CONFLICT (organization_id, name) DO NOTHING;

  INSERT INTO channels (organization_id, name, display_name, description, type)
  VALUES (NEW.id, 'general', 'General', 'Company-wide discussion', 'public')
  ON CONFLICT DO NOTHING;

  INSERT INTO workspace_spaces (organization_id, name, description, visibility)
  VALUES (NEW.id, 'Company Wiki', 'Shared knowledge base', 'organization')
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$;

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  The notification toggles, enforced at the table.
 * ═══════════════════════════════════════════════════════════════════════════
 *
 *  ── Why a trigger and not a check in `notify_members()` ──────────────────
 *
 *  `notify_members()` is the *main* way notifications are written, and it is
 *  not the only one: `notify_task_assignment()` and the leave-decision trigger
 *  in 0004 both INSERT into `notifications` directly, and predate it. Putting
 *  the gate in `notify_members()` would have left task assignment — the single
 *  most frequent notification in the product — unaffected by its own switch,
 *  which is exactly the class of "setting that does nothing" this work exists
 *  to remove.
 *
 *  A BEFORE INSERT trigger on the table cannot be bypassed by a call site that
 *  has not heard of it, including ones added later. Returning NULL drops the
 *  row silently, which is what "off" means: filtering on the way *out* would
 *  still cost a row and an index entry per suppressed event, on every task
 *  update in the organisation, forever.
 *
 *  ── The vocabulary ───────────────────────────────────────────────────────
 *
 *  Types are granular and already established — `task_assigned`,
 *  `invoice_overdue`, `leave_requested`. Rather than make the settings screen
 *  invent a coarser vocabulary that would then have to be mapped (and would
 *  drift), a toggle may be keyed either by the exact type or by its family:
 *  `task_assigned` is matched by a key of `task_assigned` first, then `task`.
 *  So one switch labelled "Task activity" governs assignment, completion and
 *  blocking, and a future deployment can still disable one of them precisely.
 *
 *  Absent or malformed settings mean deliver. An organisation that has never
 *  opened the screen, or a type nothing has a toggle for yet, must not go
 *  silent.
 */
CREATE OR REPLACE FUNCTION public.notification_enabled(org uuid, ntype text)
RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  enabled jsonb;
  family  text;
BEGIN
  IF org IS NULL OR ntype IS NULL THEN RETURN true; END IF;

  SELECT value INTO enabled
  FROM org_settings
  WHERE organization_id = org AND key = 'notification_events';

  IF enabled IS NULL THEN RETURN true; END IF;

  -- The exact type wins when it is configured.
  IF enabled ? ntype THEN
    RETURN COALESCE((enabled ->> ntype) <> 'false', true);
  END IF;

  -- Otherwise the family: everything before the first underscore.
  family := split_part(ntype, '_', 1);
  IF enabled ? family THEN
    RETURN COALESCE((enabled ->> family) <> 'false', true);
  END IF;

  RETURN true;
END;
$$;

GRANT EXECUTE ON FUNCTION public.notification_enabled(uuid, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.drop_disabled_notification()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF public.notification_enabled(NEW.organization_id, NEW.type) THEN
    RETURN NEW;
  END IF;
  -- Dropped, not raised: a suppressed notification is a configuration choice,
  -- not an error, and must never fail the business write that triggered it.
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_drop_disabled_notification ON notifications;
CREATE TRIGGER trg_drop_disabled_notification
  BEFORE INSERT ON notifications
  FOR EACH ROW EXECUTE FUNCTION public.drop_disabled_notification();

/**
 * `departments.head_id` gains the foreign key its own comment claims.
 *
 * The column has existed since 0001, described there as "a membership, not a
 * bare user: it must be someone in this org" — and carrying no constraint at
 * all. Nothing could write it until now, so nothing had tested the claim. With
 * the administration screen able to assign a manager, an unconstrained uuid
 * column would accept a membership from another tenant, which is a
 * cross-organisation reference in the middle of the org chart.
 *
 * ON DELETE SET NULL rather than CASCADE: removing a person should leave the
 * department without a manager, not delete the department.
 */
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'departments_head_fk') THEN
    -- Anything already pointing nowhere is cleared first, or the constraint
    -- cannot be added.
    UPDATE departments d SET head_id = NULL
     WHERE head_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM organization_members om WHERE om.id = d.head_id);

    ALTER TABLE departments
      ADD CONSTRAINT departments_head_fk
      FOREIGN KEY (head_id) REFERENCES organization_members(id) ON DELETE SET NULL;
  END IF;
END $$;


-- ───────────────────────────────────────────────────────────────────────────
--  7. Reading views
-- ───────────────────────────────────────────────────────────────────────────

/**
 * The workspace tree, with the caller's permission resolved per row.
 *
 * The client needs to know whether to show a rename control before the user
 * clicks it; computing that in the browser would mean shipping the sharing
 * rules to it, which is both duplication and a disclosure.
 */
CREATE OR REPLACE VIEW public.v_workspace_tree
WITH (security_invoker = true) AS
SELECT
  p.id,
  p.organization_id,
  p.space_id,
  p.parent_id,
  p.title,
  p.icon,
  p.colour,
  p.kind,
  p.is_folder,
  p.is_template,
  p.is_starred,
  p.visibility,
  p.department_id,
  p.sort_order,
  p.version,
  p.created_by,
  p.last_edited_by,
  p.created_at,
  p.updated_at,
  d.name                        AS department_name,
  editor.full_name              AS last_edited_by_name,
  creator.full_name             AS created_by_name,
  public.page_permission(p.id)  AS permission,
  (SELECT COUNT(*)::int FROM workspace_pages c
    WHERE c.parent_id = p.id AND c.deleted_at IS NULL) AS child_count,
  (SELECT COUNT(*)::int FROM files f
    WHERE f.page_id = p.id AND f.deleted_at IS NULL)   AS file_count,
  (SELECT COUNT(*)::int FROM workspace_page_shares s
    WHERE s.page_id = p.id)                            AS share_count
FROM workspace_pages p
LEFT JOIN departments d           ON d.id = p.department_id
LEFT JOIN organization_members em ON em.id = p.last_edited_by
LEFT JOIN profiles editor         ON editor.id = em.user_id
LEFT JOIN organization_members cm ON cm.id = p.created_by
LEFT JOIN profiles creator        ON creator.id = cm.user_id
WHERE p.deleted_at IS NULL;

GRANT SELECT ON public.v_workspace_tree TO authenticated;

COMMENT ON VIEW public.v_workspace_tree IS
  'Workspace pages and folders with the caller''s effective permission '
  'resolved per row. security_invoker keeps RLS on workspace_pages in force, '
  'so this view can only ever show rows the caller could already read.';

/**
 * Files with their uploader and their place in the workspace.
 *
 * A separate view rather than an embed on the files endpoint, because the same
 * shape is wanted by the project deliverables tab and the HR documents tab,
 * and three PostgREST select strings for one join is how they drift.
 */
CREATE OR REPLACE VIEW public.v_files
WITH (security_invoker = true) AS
SELECT
  f.id,
  f.organization_id,
  f.bucket,
  f.path,
  f.filename,
  f.mime_type,
  f.size_bytes,
  f.description,
  f.version,
  f.page_id,
  f.project_id,
  f.task_id,
  f.ticket_id,
  f.member_id,
  f.is_confidential,
  f.uploaded_by,
  f.created_at,
  f.updated_at,
  p.title       AS folder_title,
  up.full_name  AS uploaded_by_name,
  up.avatar_url AS uploaded_by_avatar,
  proj.name     AS project_name,
  -- Appended rather than inserted: Postgres permits adding columns to the end
  -- of a view definition but not reordering them, and CREATE OR REPLACE on a
  -- view that already exists fails with "cannot change name of view column".
  f.folder,
  f.is_client_visible
FROM files f
LEFT JOIN workspace_pages p        ON p.id = f.page_id
LEFT JOIN projects proj            ON proj.id = f.project_id
LEFT JOIN organization_members om  ON om.id = f.uploaded_by
LEFT JOIN profiles up              ON up.id = om.user_id
WHERE f.deleted_at IS NULL;

GRANT SELECT ON public.v_files TO authenticated;

/**
 * Channel participants, with names, for the members panel.
 *
 * Reading `channel_members` alone gives membership ids; every screen that
 * shows a participant list then has to join to profiles itself, and the two
 * places that already did it spelled the relation differently.
 */
-- Dropped first rather than replaced. `db:apply` re-runs every migration, and
-- 0019 extends this view with further columns — so on the second run this
-- statement would be replacing the wider view with the narrower one, which
-- Postgres refuses with "cannot drop columns from view". Recreating from
-- scratch keeps the chain re-runnable; 0019 then re-adds its columns as it
-- did the first time. Same fix as 0007 needed after 0012 extended
-- v_org_directory.
DROP VIEW IF EXISTS public.v_channel_members CASCADE;

CREATE VIEW public.v_channel_members
WITH (security_invoker = true) AS
SELECT
  cm.id,
  cm.channel_id,
  cm.member_id,
  cm.role,
  cm.is_muted,
  cm.last_read_at,
  cm.joined_at,
  c.organization_id,
  p.full_name,
  p.avatar_url,
  p.email,
  p.job_title,
  p.last_seen_at,
  om.role       AS org_role,
  d.name        AS department_name
FROM channel_members cm
JOIN channels c                   ON c.id = cm.channel_id
JOIN organization_members om      ON om.id = cm.member_id
JOIN profiles p                   ON p.id = om.user_id
LEFT JOIN departments d           ON d.id = om.department_id;

GRANT SELECT ON public.v_channel_members TO authenticated;


-- ───────────────────────────────────────────────────────────────────────────
--  8. Indexes for the new access paths
-- ───────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_pages_kind
  ON workspace_pages (organization_id, kind) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pages_starred
  ON workspace_pages (organization_id, is_starred) WHERE deleted_at IS NULL AND is_starred = true;
CREATE INDEX IF NOT EXISTS idx_channels_org_type
  ON channels (organization_id, type) WHERE is_archived = false;
CREATE INDEX IF NOT EXISTS idx_page_versions_page
  ON workspace_page_versions (page_id, version DESC);
